### ISSUE TITLE
post build conditional step is not triggering a build using the below script

### ISSUE THREAD

**Issue by ranjitkumar518** [jjasghar/jenkins-jobs#1]
- job:
    name: 'maven_job'
    project-type: maven
    description: "Modified job"
    concurrent: false
    scm:
      - git:
          url: https://github.com/ranjitkumar518/myfirstrepo.git
          branches:
            - '${branch}'
    maven:
       maven-name: maven-3.2.1
       root-pom: pom.xml
       goals: clean package
    #post build step for conditional shell and trigger a job using this script with block: true
    builders:
       - conditional-step:
             condition-kind: current-status
             condition-worst: SUCCESS
             condition-best: SUCCESS
             on-evaluation-failure: fail
             steps:
                - shell: "ls -la /etc"

**Comment by ranjitkumar518** [comment]
I am trying to create a job using jjb tool to trigger a build on successful conditional-step. please help me on this issue to trigger a job.
 
Regards
~Ranjit

**Comment by jjasghar** [comment]
I'd reach out to the #openstack team on freenode for this. Debugging this through issues on github is probably more challenging than it should be.
